module Kangaru
  module Validation
    class AttributeValidator
      type validations = Hash[Symbol, rule]
      type rule = bool | Hash[Symbol, untyped]

      attr_reader model: untyped
      attr_reader attribute: Symbol

      def initialize: (model: untyped, attribute: Symbol) -> void

      def validate!: (**untyped) -> void

      private

      def load_validator: (validator: Symbol, **untyped) -> Validator
    end
  end
end
