module Kangaru
  module Validation
    class Error
      attr_reader attribute: Symbol
      attr_reader message: String

      def initialize: (attribute: Symbol, message: String) -> void

      def full_message: -> String

      private

      def human_attribute: -> String
    end
  end
end
