module Kangaru
  module Configurators
    class BaseConfigurator
      self.@settings: Array[Symbol]

      def self.name: -> Symbol

      def self.settings: -> Array[Symbol]

      def serialise: -> Hash[Symbol, untyped]
    end
  end
end
