module Kangaru
  module Configurators
    class Configurator
      include Concerns::AttributesConcern
      extend  Concerns::AttributesConcern::ClassMethods

      def self.name: -> Symbol

      def serialise: -> Hash[Symbol, untyped]
    end
  end
end
