module Kangaru
  module Configurators
    class OpenConfigurator < Configurator
      def self.from_yaml_file: (String) -> instance

      private

      def set_accessors!: (**untyped) -> void
    end
  end
end
