module Kangaru
  module Inflectors
    module InflectorMacros
      @token_transformer: untyped
      @token_joiner: untyped
      @group_joiner: untyped

      def transform_tokens_with: (?Symbol?) ?{ (String) -> String } -> void

      def join_tokens_with: (String) -> void

      def join_groups_with: (String) -> void
    end
  end
end
