module Kangaru
  module InputParsers
    class InputParser
      type tokens = Array[String]

      ARGUMENT_TOKEN: Regexp

      attr_reader tokens: tokens

      def initialize: (tokens) -> void

      def parse: -> untyped

      def command_tokens: -> tokens

      def argument_tokens: -> tokens
    end
  end
end
