module Kangaru
  module Testing
    class Gem
      include GemPaths

      DEFAULT_NAME: String

      attr_reader dir: String
      attr_reader name: String

      def initialize: (dir: String, ?name: String) -> void

      def create!: -> void
    end
  end
end
