module Kangaru
  module Testing
    class Gem
      DEFAULT_NAME: String

      attr_reader dir: String
      attr_reader name: String

      def initialize: (dir: String, ?name: String) -> void

      def create!: -> void

      private

      attr_reader gem_path: String
    end
  end
end
