module Kangaru
  VERSION: String
  INFLECTIONS: Hash[String, String]

  extend ClassMethods

  module ClassMethods
    @loader: Zeitwerk::Loader

    attr_accessor application: Application
    attr_accessor env: Symbol

    def env?: (Symbol) -> bool

    def eager_load: (Module) -> void

    def test?: -> bool
  end

  # Included in target applications that extend Kangaru::Initialiser.
  interface _ApplicationMethods
    def run!: (Array[String]) -> void

    def config: -> Config

    def configure: { (Config) -> void } -> void

    def database: -> Database?
  end
end
