module Kangaru
  class Application
    extend Forwardable

    class InvalidConfigError < StandardError
    end

    attr_reader paths: Paths
    attr_reader namespace: Module
    attr_reader database: Database?

    attr_accessor config_path: String

    attr_reader config: Config
    attr_reader router: Router

    def initialize: (source: String, namespace: Module) -> void

    def configure: (?Symbol?) { (Config) -> void } -> void

    def configured?: -> bool

    def apply_config!: -> void

    def run!: (*String) -> void

    def const_get: (String | Symbol) -> Module?
                 | (String | Symbol) -> Class?

    # Delegated to paths
    def view_path: (*String, ?ext: Symbol?) -> Pathname

    private

    @configured: bool

    def current_env?: (Symbol?) -> bool

    attr_reader autoloader: Zeitwerk::Loader

    def validate_config!: -> void

    def setup_database!: -> Database?
  end
end
