module Kangaru
  interface _Application
    def dir: -> Pathname
    def name: -> String
  end

  module ApplicationPaths : _Application
    VIEWS_DIR: String

    attr_reader path: Pathname

    attr_reader lib_path: Pathname

    attr_reader main_file: Pathname

    def gem_file: (String file) -> Pathname

    def gem_dir: (String dir) -> Pathname

    def view_file: (controller: String, action: String) -> Pathname
  end
end
