module Kangaru
  class Application
    include ApplicationPaths

    attr_reader name: String
    attr_reader dir: String
    attr_reader namespace: Module
    attr_reader config: Config
    attr_reader database: Database

    def initialize: (name: String, dir: String, namespace: Module) -> void

    def configure: { (Config) -> void } -> void

    def run!: (Array[String]) -> void

    def self.from_callsite: (String callsite, namespace: Module) -> Application

    private

    attr_reader autoloader: Zeitwerk::Loader

    def setup: -> void
  end
end
