module Kangaru
  class Command
    attr_reader controller: String
    attr_reader action: Symbol
    attr_reader arguments: Hash[Symbol, untyped]

    def initialize: (
      controller: String,
      action: Symbol,
      arguments: Hash[Symbol, untyped]
    ) -> void

    def self.from_argv: (Array[String]) -> Command
  end
end
