module Kangaru
  class Configurator
    include Attributable
    extend  Attributable::ClassMethods

    include Validatable
    extend  Validatable::ClassMethods

    def self.key: -> Symbol

    def self.name: -> String

    def serialise: -> Hash[Symbol, untyped]
  end
end
