module Kangaru
  class Configurator
    include Concerns::AttributesConcern
    extend  Concerns::AttributesConcern::ClassMethods

    include Concerns::Validatable
    extend  Concerns::Validatable::ClassMethods

    def self.key: -> Symbol

    def self.name: -> String

    def serialise: -> Hash[Symbol, untyped]
  end
end
