module Kangaru
  class Config
    type configurator = Configurators::Configurator

    attr_reader configurators: Hash[Symbol, configurator]

    def initialize: -> void

    def serialise: -> Hash[Symbol, Hash[Symbol, untyped]]

    def import_external_config!: -> void

    def for: (String) -> untyped

    # Configurators
    attr_reader application: Configurators::ApplicationConfigurator
    attr_reader database:    Configurators::DatabaseConfigurator
    attr_reader external:    Configurators::ExternalConfigurator
    attr_reader request:     Configurators::RequestConfigurator

    private

    def set_configurators!: -> Hash[Symbol, configurator]

    def external_config_exists?: -> bool
  end
end
