module Kangaru
  class Config
    type configurator = Configurators::BaseConfigurator

    attr_reader configurators: Hash[Symbol, configurator]

    def initialize: -> void

    def serialise: -> Hash[Symbol, Hash[Symbol, untyped]]

    private

    def set_configurators!: -> Hash[Symbol, configurator]
  end
end
