module Kangaru
  class Controller
    SUFFIX: String

    attr_reader request: Request

    def initialize: (Request) -> void

    def execute: -> void

    def self.path: -> String
    
    private

    def view_path: (String) -> Pathname

    def renderer_for: (String) -> Renderer
  end
end
