module Kangaru
  class Controller
    SUFFIX: String

    attr_reader request: Request

    def initialize: (Request) -> void

    def view_file: -> Pathname

    def execute: -> void

    def self.path: -> String
    
    private

    attr_reader renderer: Renderer
  end
end
