module Kangaru
  module Initialiser
    module InjectedMethods
      def run!: (Array[String]) -> void

      def config: -> Config

      def configure: { (Config) -> void } -> void

      def database: -> Database
    end

    def self.extended: (Module) -> void
  end
end
