module Kangaru
  module InjectedMethods
    def run!: (*String) -> void

    def config: -> Config

    def configure: (?Symbol?) { (Config) -> void } -> void

    def apply_config!: -> void

    def import_config_from!: (String) -> void

    def database: -> Database?
  end
end
