module Kangaru
  class InputParser
    ARGUMENT_TOKEN: Regexp

    attr_reader tokens: Array[String]

    def initialize: (*String) -> void

    def parse: -> Command

    private

    def command_attributes: -> {
      path: String?,
      action: Symbol?,
      id: Integer?,
      arguments: Hash[Symbol, untyped] 
    }

    def route_tokens: -> Array[String]

    def argument_tokens: -> Array[String]

    def route_attributes: -> InputParsers::RouteParser::output

    def arguments: -> Hash[Symbol, untyped]
  end
end
