module Kangaru
  module Interface
    type env = Symbol?

    def run!: (*String) -> void

    def config: -> Config

    def configure: (?env: env) { (Config) -> void } -> void

    def apply_config!: -> void

    def config_path: (String, ?env: env) -> void

    def database: -> Database?

    private

    def env_applies?: (Symbol?) -> bool
  end
end
