module Kangaru
  class Router
    class UndefinedControllerError < StandardError
    end

    class UndefinedActionError < StandardError
    end

    CONTROLLER_SUFFIX: String

    attr_reader command: LegacyCommand
    attr_reader namespace: Module

    def initialize: (LegacyCommand, ?namespace: Module) -> void

    def resolve: -> void

    private

    @controller_name: String
    @controller_class: untyped

    def controller_name: -> String

    def controller_class: -> untyped

    def validate_controller_defined!: -> void

    def validate_action_defined!: -> void
  end
end
