module Kangaru
  module Concerns
    module Configurable
      extend Concern
      extend ClassMethods

      module ClassMethods
        def configurator_name: -> String
      end

      def name: -> String
      def config: -> Configurators::Configurator
    end
  end
end
