module Kangaru
  module Validatable
    type validations = Hash[Symbol, Hash[Symbol, untyped]]

    extend Concern
    extend ClassMethods

    attr_reader validation_rules: validations

    module ClassMethods
      attr_reader validation_rules: validations

      def validates: (Symbol, **untyped) -> void
    end

    attr_reader errors: Array[Validation::Error]

    def validate: -> void

    def valid?: -> bool

    private

    attr_reader model_validator: Validation::ModelValidator
  end
end
