module Zeitwerk
  class Loader
    attr_accessor inflector: GemInflector

    def self.for_gem: (?warn_on_extra_files: bool) -> instance

    def collapse: (Array[String]) -> void

    def push_dir: (String dir, ?namespace: Module) -> void

    def setup: -> void
  end
end
